version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_USER}
  app:
    build: .
    image: levelling-system
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:3000
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      - db

volumes:
  db-vol:
