version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  my-db:
